FROM gradle:latest AS build
WORKDIR /usr/app
COPY barebonesystem .
RUN gradle clean build

FROM openjdk:21-ea-26-jdk-oraclelinux8
WORKDIR /etc/app/build
COPY --from=build /usr/app/build/libs/barebonesystem-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
