FROM node:latest AS react-build
WORKDIR /usr/static/src/react-app
COPY ui .
ENV REACT_APP_API_URL=http://localhost:8000/api/v1
RUN npm install
RUN npm run build

FROM nginx:stable-alpine
COPY --from=react-build /usr/static/src/react-app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
